const PDFDocument = require('pdfkit')

const ACCENT = '#16a34a'
const INK = '#111111'
const MUTED = '#666666'
const RULE = '#dddddd'

function money(value) {
  return `$${(parseFloat(value) || 0).toFixed(2)}`
}

function formatDate(iso) {
  return new Date(iso || Date.now()).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
}

/**
 * Render a purchase order to a PDF buffer.
 *
 * Buffers rather than streams: the PDF is emailed as an attachment and also
 * served for download, and both need the whole document anyway. Purchase
 * orders are a page or two, so holding one in memory is not a concern.
 */
function buildPurchaseOrderPdf({ order, lines, organizationName }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 })
      const chunks = []

      doc.on('data', chunk => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      const left = doc.page.margins.left
      const right = doc.page.width - doc.page.margins.right
      const width = right - left

      // --- Header -----------------------------------------------------
      doc.fillColor(ACCENT).fontSize(24).font('Helvetica-Bold')
        .text('PURCHASE ORDER', left, 50)

      doc.fillColor(MUTED).fontSize(10).font('Helvetica')
        .text(order.reference, left, 80)

      doc.fillColor(INK).fontSize(12).font('Helvetica-Bold')
        .text(organizationName || 'TechIT', left, 50, { width, align: 'right' })

      doc.fillColor(MUTED).fontSize(9).font('Helvetica')
        .text(formatDate(order.created_at), left, 68, { width, align: 'right' })

      doc.moveTo(left, 105).lineTo(right, 105).strokeColor(RULE).lineWidth(1).stroke()

      // --- Supplier ---------------------------------------------------
      let y = 125
      doc.fillColor(MUTED).fontSize(9).font('Helvetica-Bold').text('SUPPLIER', left, y)
      y += 14
      doc.fillColor(INK).fontSize(12).font('Helvetica-Bold').text(order.supplier_name, left, y)
      if (order.supplier_email) {
        y += 16
        doc.fillColor(MUTED).fontSize(10).font('Helvetica').text(order.supplier_email, left, y)
      }

      // --- Line items table -------------------------------------------
      y += 40

      // Column x-positions, right-aligned numerics sized to their headers
      const colSku = left
      const colName = left + 100
      const colQty = left + 300
      const colCost = left + 370
      const colTotal = left + 435

      doc.fillColor(MUTED).fontSize(9).font('Helvetica-Bold')
      doc.text('SKU', colSku, y)
      doc.text('ITEM', colName, y)
      doc.text('QTY', colQty, y, { width: 50, align: 'right' })
      doc.text('UNIT COST', colCost, y, { width: 70, align: 'right' })
      doc.text('TOTAL', colTotal, y, { width: 85, align: 'right' })

      y += 16
      doc.moveTo(left, y).lineTo(right, y).strokeColor(RULE).stroke()
      y += 12

      doc.font('Helvetica').fontSize(10)

      lines.forEach(line => {
        // Start a new page before the row rather than splitting it
        if (y > doc.page.height - 140) {
          doc.addPage()
          y = 60
        }

        doc.fillColor(MUTED).fontSize(9)
          .text(line.sku, colSku, y, {
            width: 95, height: 11, ellipsis: true, lineBreak: false,
          })

        doc.fillColor(INK).fontSize(10)
          .text(line.item_name, colName, y, {
            width: 190, height: 12, ellipsis: true, lineBreak: false,
          })

        doc.text(String(line.quantity_ordered), colQty, y, { width: 50, align: 'right' })
        doc.text(money(line.unit_cost), colCost, y, { width: 70, align: 'right' })
        doc.font('Helvetica-Bold')
          .text(money(line.line_total), colTotal, y, { width: 85, align: 'right' })
        doc.font('Helvetica')

        // Why this line is on the order
        y += 14
        doc.fillColor(MUTED).fontSize(8)
          .text(
            `on hand ${line.quantity_at_order} · reorder below ${line.threshold_at_order}`,
            colName, y, { width: 190 }
          )

        y += 18
      })

      // --- Total ------------------------------------------------------
      doc.moveTo(left, y).lineTo(right, y).strokeColor(RULE).stroke()
      y += 12

      doc.fillColor(MUTED).fontSize(10).font('Helvetica')
        .text('Order total', left, y, { width: colTotal - left - 10, align: 'right' })
      doc.fillColor(ACCENT).fontSize(14).font('Helvetica-Bold')
        .text(money(order.total_cost), colTotal, y - 3, {
          width: 85, align: 'right', lineBreak: false,
        })

      // --- Footer -----------------------------------------------------
      doc.fillColor(MUTED).fontSize(8).font('Helvetica')
        .text(
          `Generated by TechIT Inventory Management · ${formatDate(order.created_at)}`,
          left, doc.page.height - 70, { width, align: 'center' }
        )

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

module.exports = { buildPurchaseOrderPdf }
